### ISSUE TITLE
参数无效

### ISSUE THREAD

**Issue by loveloving** [a67793581/robot-web-hook#2]
mentioned_list 和 mentioned_mobile_list 配置无效

**Comment by a67793581** [comment]
你是怎么测试的 请详细描述一下

**Comment by loveloving** [comment]
我知道了, MarkDown类型需把手机号放到text里面, 才会@成功; 
参考文档: https://blog.csdn.net/qq_37530065/article/details/106305295

**Comment by a67793581** [comment]
嗯 关闭了
